import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: PropsWithChildren) => (
  <html lang="en">
    <body
      style={{
        height: '100vh',
        margin: '0',
        padding: '0'
      }}
    >
      {children}
    </body>
  </html>
);

export default RootLayout;
